# Store useful data about Reddit Collectible Avatars collections in order
# to reason about them when getting blockchain data.

# Enter your address below, but use generated CONTRACT_ADDRESS_TO_COLLECTION_SLUG.
USER_ENTERED_CONTRACT_ADDRESS_TO_COLLECTION_SLUG = {
    # Season 1
    "0x5846728730366d686cdc95dae80a70b44ec9eab2": "imagination-station-x-reddit-collectible-avatars",
    "0xfbed9640e37666fe2ac78e1d263670976354cb69": "the-butterfly-garden-x-reddit-collectible-avatars",
    "0xe0743141df04a6b9f3df890429cc994e46db03d9": "drag-queens-of-big-gay-baby-x-reddit-collectible",
    "0x97439ee4c93ff9f76417696ce648aa6f35ab3b25": "creatures-of-the-nighties-x-reddit-collectible",
    "0xf43bc3f4F1edb7d4C373C8510A2888d69d83cEB7": "joy-girls-club-x-reddit-collectible-avatars",
    "0x425bf054Ef7bAD65B7BDd8E6587B1c3500E4F4CA": "avatar-rock-out-x-reddit-collectible-avatars",
    "0x2956409293da98603025Cc0121C06A4244752039": "protectors-of-the-forest-x-reddit-collectible-avat",
    "0xa7Bb50d90B43752199c45Be04053641C3cb5f53f": "bites-of-brazil-x-reddit-collectible-avatars",
    "0x47749C5B970e63F3a0ed57Cd6ceF773E74FaFe9d": "cute-cool-and-creepy-x-reddit-collectible-avatars",
    "0x838c1CD42929543daF9C3ef294Fee8c1b3224B37": "creatures-without-pants-x-reddit-collectible-avata",
    "0xC5Aa1F91b0d52e26D2847f8e51f505d6e2ECe795": "lightspeed-lads-x-reddit-collectible-avatars",
    "0xeE1Ee80338958fA596471CEb70F0177DafF80323": "growl-gang-x-reddit-collectible-avatars",
    "0x4670e4890Bc1b76F3aE5c7660aA98E0B6668C6F3": "old-school-cool-x-reddit-collectible-avatars",
    "0x2d58a44d6c0a355de25761fb33a1f6269a97e2c5": "aylia-x-reddit-collectible-avatars",
    "0xD8cF23bF309DE778609d234BD2410B0156118c26": "magic-of-the-woods-x-reddit-collectible-avatars",
    "0x91E51B92a2EfEA89bF1B6f66ad719737264724bE": "cute-snacks-x-reddit-collectible-avatars",
    "0xd6261320F49d38c137f6e229a2EA4Ab0F4Fae6DE": "peculiar-gang-x-reddit-collectible-avatars",
    "0xFC190440E8f357fFE8A75940e7D8A291E165d019": "gettin-groovy-x-reddit-collectible-avatars",
    "0x808ED3E23aac685126524aA4416d8eaeB2E767B9": "wearing-your-emotions-x-reddit-collectible-avatars",
    "0x65a83530Ca8abc27969907913Fe5E641a5DA2e9f": "i-quit-my-job-to-be-an-artist-x-reddit-collectibl",
    "0x6d1c3646e8Cce8537E6ec9eCAb26762bfAf1f891": "baked-goods-evils-x-reddit-collectible-avatars",
    "0x63e2f0C058Ce9A194eC68F04320b7Eb8cA555BD3": "enlightenment-x-reddit-collectible-avatars",
    "0x45308788743bBDAe5DE7ba9e565c0502d0EBb81F": "doodle-collection-x-reddit-collectible-avatars",
    "0x907808732079863886443057C65827a0F1c64357": "foustlings-x-reddit-collectible-avatars",
    "0x8D0501d85becDA92B89E56177dDfcEA5Fc1f0AF2": "the-senses-x-reddit-collectible-avatars",
    "0x6ad08588568E258b2BdF065e7769FCE398F68A1C": "the-minds-eyes-x-reddit-collectible-avatars",
    "0x946aD8E53db653053E8ef7C02DFCA83ce8bA8022": "natsukashii-x-reddit-collectible-avatars",
    "0x27B37E4Befacc50B02102d1E2117c4EA8A54bEFf": "5-boro-bodega-x-reddit-collectible-avatars",
    "0x71DC46607F31f30510f0ccc670B0963F431b212A": "celestial-assembly-x-reddit-collectible-avatars",
    # Season 2
    "0x45ee1caed83525673843321107bccadecb9065d7": "spooky-season-tirli-x-reddit-collectible-avatars",
    "0x81ba34b90876f42f34a4f232cfc0fe4b6ec949a3": "spooky-season-stuttervoid-x-reddit-collectible-ava",
    "0x5fd4d6fef3b87b91c7df8658727b5edd7210cf5a": "spooky-season-substantial-law-910-x-reddit-collect",
    "0xe4989961ebfdac3e65fcf0059c916452c77d8503": "spooky-season-worsttwitchever-x-reddit-collectible",
    "0x3e4627665bf2e52c69be03788e664ab545f2be71": "spooky-season-rojom-x-reddit-collectible-avatars",
    "0x91ac106090fe2b0fa7d01efdf4487a5bfafad7fa": "spooky-season-poieeeyee-x-reddit-collectible-avata",
    "0xddbdb65138131dbf2d01b4a5140e1979680c90bb": "spooky-season-aliciafreemandesigns-x-reddit-collec",
    "0xc70a7496716b3e25546901fe88215531abbd5a10": "spooky-season-genuineardvark-x-reddit-collectible",
    "0x8264e2bad3d2f7afd72a00233b9f841fe4b388cd": "spooky-season-earthtoplanet-x-reddit-collectible-a",
    "0x2e90e8af4c319095942c84cfa446e1f206795517": "spooky-season-oana193-x-reddit-collectible-avatars",
    "0xe1b5e23fdbc003aec16e6e79726a0b5f75ff93f5": "spooky-season-tfoust10-x-reddit-collectible-avatar",
    "0x3458161f2dc5d7eafa48e7c8d9acd7f415cf6da6": "spooky-season-conall-in-space-x-reddit-collectible",
    "0x04125a97a0f2583cd485be2c34b651cc13c38a27": "spooky-season-avirenft-x-reddit-collectible-ava",
    "0x621ce7e7e44d43a428a183d5390c4f4572c9ff9d": "spooky-season-eando9745-x-reddit-collectible-avata",
    "0xd5ae5a16fbaf964f96e242645a4a6f10b98fd0c4": "spooky-season-dubbl3bee-x-reddit-collectible-avata",
    "0xbc096988fa38c78d65c0637453fd3d3c38b1cfd4": "spooky-season-raunchyrancor-x-reddit-collectible-a",
    "0x150afa2dfcaaada471472dfa6ad4b79e718a197c": "spooky-season-treasureofophiel-x-reddit-collectibl",
    "0x04f087e3191d7a050800a2e04cb20046d2633e35": "spooky-season-puzzled-panther-x-reddit-collectible",
    "0x0985cb10c5d57dbf44aa473f33839ed38d80f111": "spooky-season-thefattybagz-x-reddit-collectible-av",
    "0x21d426e2b88fbf8b93adf0591a2d5b08d58f089f": "spooky-season-baldtuesdays-x-reddit-collectible",
    "0x334ad326a787dd332f26cbe8b4d7adfa8bd25f92": "spooky-season-laura-dumitriu-x-reddit-collectible",
    "0xdaa6e4ba2d4022ed820460bb501b9e061d9614fb": "spooky-season-sys32template-x-reddit-collectible-a",
    "0x7e680862c572e4b945cf45912130c8d884109b59": "spooky-season-bodegacatceo-x-reddit-collectible-av",
    "0x37db2523d221d19838632eb62d1af911e52632c3": "spooky-season-tandizojere-x-reddit-collectible-ava",
    "0x04f7a676af597f847053b6c02ed42d02fa4046aa": "spooky-season-canetoonist-x-reddit-collectible-ava",
    "0xfec90bc707fc93aefeb0c18c2eb56bc79d32163e": "spooky-season-fmarxy-x-reddit-collectible-avatars",
    "0x83feea011baeb1c6d1df7d23903efad83d3c781f": "spooky-season-hoppy-doodle-x-reddit-collectible-av",
}

CONTRACT_ADDRESS_TO_COLLECTION_SLUG = {}
for contract in USER_ENTERED_CONTRACT_ADDRESS_TO_COLLECTION_SLUG:
    CONTRACT_ADDRESS_TO_COLLECTION_SLUG[contract.lower()] = USER_ENTERED_CONTRACT_ADDRESS_TO_COLLECTION_SLUG[contract]

COLLECTION_SLUG_TO_NAME = {
    "imagination-station-x-reddit-collectible-avatars": "Imagination Station x Reddit Collectible Avatars",
    "the-butterfly-garden-x-reddit-collectible-avatars": "The Butterfly Garden x Reddit Collectible Avatars",
    "drag-queens-of-big-gay-baby-x-reddit-collectible": "Drag Queens of Big Gay Baby x Reddit Collectible Avatars",
    "creatures-of-the-nighties-x-reddit-collectible": "Creatures of the Nighties x Reddit Collectible Avatars",
    "joy-girls-club-x-reddit-collectible-avatars": "Joy Girls Club x Reddit Collectible Avatars",
    "avatar-rock-out-x-reddit-collectible-avatars": "Avatar Rock Out x Reddit Collectible Avatars",
    "protectors-of-the-forest-x-reddit-collectible-avat": "Protectors of the Forest x Reddit Collectible Avatars",
    "bites-of-brazil-x-reddit-collectible-avatars": "Bites of Brazil x Reddit Collectible Avatars",
    "cute-cool-and-creepy-x-reddit-collectible-avatars": "Cute, Cool and Creepy x Reddit Collectible Avatars",
    "creatures-without-pants-x-reddit-collectible-avata": "Creatures Without Pants x Reddit Collectible Avatars",
    "lightspeed-lads-x-reddit-collectible-avatars": "Lightspeed Lads x Reddit Collectible Avatars",
    "growl-gang-x-reddit-collectible-avatars": "Growl Gang x Reddit Collectible Avatars",
    "old-school-cool-x-reddit-collectible-avatars": "Old School Cool x Reddit Collectible Avatars",
    "aylia-x-reddit-collectible-avatars": "Aylia x Reddit Collectible Avatars",
    "magic-of-the-woods-x-reddit-collectible-avatars": "Magic of the Woods x Reddit Collectible Avatars",
    "cute-snacks-x-reddit-collectible-avatars": "Cute Snacks x Reddit Collectible Avatars",
    "peculiar-gang-x-reddit-collectible-avatars": "Peculiar Gang x Reddit Collectible Avatars",
    "gettin-groovy-x-reddit-collectible-avatars": "Gettin' Groovy x Reddit Collectible Avatars",
    "wearing-your-emotions-x-reddit-collectible-avatars": "Wearing Your Emotions x Reddit Collectible Avatars",
    "i-quit-my-job-to-be-an-artist-x-reddit-collectibl": "I quit my job to be an Artist x Reddit Collectible Avatars",
    "baked-goods-evils-x-reddit-collectible-avatars": "Baked Goods & Evils x Reddit Collectible Avatars",
    "enlightenment-x-reddit-collectible-avatars": "Enlightenment x Reddit Collectible Avatars",
    "doodle-collection-x-reddit-collectible-avatars": "Doodle Collection x Reddit Collectible Avatars",
    "foustlings-x-reddit-collectible-avatars": "Foustlings x Reddit Collectible Avatars",
    "the-senses-x-reddit-collectible-avatars": "The Senses x Reddit Collectible Avatars",
    "the-minds-eyes-x-reddit-collectible-avatars": "The Mind's Eye(s) x Reddit Collectible Avatars",
    "natsukashii-x-reddit-collectible-avatars": "Natsukashii x Reddit Collectible Avatars",
    "5-boro-bodega-x-reddit-collectible-avatars": "5 Boro Bodega x Reddit Collectible Avatars",
    "celestial-assembly-x-reddit-collectible-avatars": "Celestial Assembly x Reddit Collectible Avatars",
    "spooky-season-tirli-x-reddit-collectible-avatars": "Spooky Season: tirli x Reddit Collectible Avatars",
    "spooky-season-stuttervoid-x-reddit-collectible-ava": "Spooky Season: StutterVoid x Reddit Collectible Avatars",
    "spooky-season-substantial-law-910-x-reddit-collect": "Spooky Season: Substantial-Law-910 x Reddit Collectible Avatars",
    "spooky-season-worsttwitchever-x-reddit-collectible": "Spooky Season: WorstTwitchEver x Reddit Collectible Avatars",
    "spooky-season-rojom-x-reddit-collectible-avatars": "Spooky Season: Rojom x Reddit Collectible Avatars",
    "spooky-season-poieeeyee-x-reddit-collectible-avata": "Spooky Season: poieeeyee x Reddit Collectible Avatars",
    "spooky-season-aliciafreemandesigns-x-reddit-collec": "Spooky Season: AliciaFreemanDesigns x Reddit Collectible Avatars",
    "spooky-season-genuineardvark-x-reddit-collectible": "Spooky Season: GenuineArdvark x Reddit Collectible Avatars",
    "spooky-season-earthtoplanet-x-reddit-collectible-a": "Spooky Season: EarthToPlanet x Reddit Collectible Avatars",
    "spooky-season-oana193-x-reddit-collectible-avatars": "Spooky Season: oana193 x Reddit Collectible Avatars",
    "spooky-season-tfoust10-x-reddit-collectible-avatar": "Spooky Season: tfoust10 x Reddit Collectible Avatars",
    "spooky-season-conall-in-space-x-reddit-collectible": "Spooky Season: Conall-in-Space x Reddit Collectible Avatars",
    "spooky-season-avirenft-x-reddit-collectible-ava": "Spooky Season: AVIRENFT x Reddit Collectible Avatars",
    "spooky-season-eando9745-x-reddit-collectible-avata": "Spooky Season: eando9745 x Reddit Collectible Avatars",
    "spooky-season-dubbl3bee-x-reddit-collectible-avata": "Spooky Season: dubbl3bee x Reddit Collectible Avatars",
    "spooky-season-raunchyrancor-x-reddit-collectible-a": "Spooky Season: RaunchyRancor x Reddit Collectible Avatars",
    "spooky-season-treasureofophiel-x-reddit-collectibl": "Spooky Season: TreasureOfOphiel x Reddit Collectible Avatars",
    "spooky-season-puzzled-panther-x-reddit-collectible": "Spooky Season: puzzled__panther x Reddit Collectible Avatars",
    "spooky-season-thefattybagz-x-reddit-collectible-av": "Spooky Season: TheFattyBagz x Reddit Collectible Avatars",
    "spooky-season-baldtuesdays-x-reddit-collectible": "Spooky Season: BaldTuesdays x Reddit Collectible Avatars",
    "spooky-season-laura-dumitriu-x-reddit-collectible": "Spooky Season: Laura_Dumitriu x Reddit Collectible Avatars",
    "spooky-season-sys32template-x-reddit-collectible-a": "Spooky Season: Sys32Template x Reddit Collectible Avatars",
    "spooky-season-bodegacatceo-x-reddit-collectible-av": "Spooky Season: bodegacatceo x Reddit Collectible Avatars",
    "spooky-season-tandizojere-x-reddit-collectible-ava": "Spooky Season: tandizojere x Reddit Collectible Avatars",
    "spooky-season-canetoonist-x-reddit-collectible-ava": "Spooky Season: Canetoonist x Reddit Collectible Avatars",
    "spooky-season-fmarxy-x-reddit-collectible-avatars": "Spooky Season: fmarxy x Reddit Collectible Avatars",
    "spooky-season-hoppy-doodle-x-reddit-collectible-av": "Spooky Season: Hoppy_Doodle x Reddit Collectible Avatars",
}

ARTISTS_TO_SLUGS = {
  "u/StutterVoid": ["wearing-your-emotions-x-reddit-collectible-avatars", "spooky-season-stuttervoid-x-reddit-collectible-ava"],
  "u/Hoppy_Doodle": ["doodle-collection-x-reddit-collectible-avatars", "spooky-season-hoppy-doodle-x-reddit-collectible-av"],
  "u/oana193": ["peculiar-gang-x-reddit-collectible-avatars", "spooky-season-oana193-x-reddit-collectible-avatars"],
  "u/Sys32Template": ["spooky-season-sys32template-x-reddit-collectible-a"],
  "u/Tandizojere": ["i-quit-my-job-to-be-an-artist-x-reddit-collectibl", "spooky-season-tandizojere-x-reddit-collectible-ava"],
  "u/GenuineArdvark": ["natsukashii-x-reddit-collectible-avatars", "spooky-season-genuineardvark-x-reddit-collectible"],
  "u/MrGrumble84": ["creatures-of-the-nighties-x-reddit-collectible"],
  "u/BaldTuesdays": ["cute-cool-and-creepy-x-reddit-collectible-avatars", "spooky-season-baldtuesdays-x-reddit-collectible"],
  "u/eando9745": ["lightspeed-lads-x-reddit-collectible-avatars", "spooky-season-eando9745-x-reddit-collectible-avata"],
  "u/fmarxy": ["bites-of-brazil-x-reddit-collectible-avatars", "spooky-season-fmarxy-x-reddit-collectible-avatars"],
  "u/tfoust10": ["foustlings-x-reddit-collectible-avatars", "spooky-season-tfoust10-x-reddit-collectible-avatar"],
  "u/Substantial-Law-910": ["the-butterfly-garden-x-reddit-collectible-avatars", "spooky-season-substantial-law-910-x-reddit-collect"],
  "u/RaunchyRancor": ["avatar-rock-out-x-reddit-collectible-avatars", "spooky-season-raunchyrancor-x-reddit-collectible-a"],
  "u/WorstTwitchEver": ["enlightenment-x-reddit-collectible-avatars", "spooky-season-worsttwitchever-x-reddit-collectible"],
  "u/ChipperdoodlesComic": ["imagination-station-x-reddit-collectible-avatars"],
  "u/Conall-in-Space": ["celestial-assembly-x-reddit-collectible-avatars", "spooky-season-conall-in-space-x-reddit-collectible"],
  "u/Rojom": ["the-senses-x-reddit-collectible-avatars", "spooky-season-rojom-x-reddit-collectible-avatars"],
  "u/Earthtoplanet": ["creatures-without-pants-x-reddit-collectible-avata", "spooky-season-earthtoplanet-x-reddit-collectible-a"],
  "u/Laura_Dumitriu": ["protectors-of-the-forest-x-reddit-collectible-avat", "spooky-season-laura-dumitriu-x-reddit-collectible"],
  "u/poieeeyee": ["spooky-season-poieeeyee-x-reddit-collectible-avata"],
  "u/Canetoonist": ["old-school-cool-x-reddit-collectible-avatars", "spooky-season-canetoonist-x-reddit-collectible-ava"],
  "u/AliciaFreemanDesigns": ["magic-of-the-woods-x-reddit-collectible-avatars", "spooky-season-aliciafreemandesigns-x-reddit-collec"],
  "u/tirli": ["cute-snacks-x-reddit-collectible-avatars", "spooky-season-tirli-x-reddit-collectible-avatars"],
  "u/TreasureOfOphiel": ["baked-goods-evils-x-reddit-collectible-avatars", "spooky-season-treasureofophiel-x-reddit-collectibl"],
  "u/TheFattyBagz": ["the-minds-eyes-x-reddit-collectible-avatars", "spooky-season-thefattybagz-x-reddit-collectible-av"],
  "u/AVIRENFT": ["aylia-x-reddit-collectible-avatars", "spooky-season-avirenft-x-reddit-collectible-ava"],
  "u/puzzled__panther": ["growl-gang-x-reddit-collectible-avatars", "spooky-season-puzzled-panther-x-reddit-collectible"],
  "u/dubbl3bee": ["avatar-rock-out-x-reddit-collectible-avatars", "spooky-season-dubbl3bee-x-reddit-collectible-avata"],
  "u/BigGayBaby_": ["drag-queens-of-big-gay-baby-x-reddit-collectible"],
  "u/bodegacatceo": ["5-boro-bodega-x-reddit-collectible-avatars", "spooky-season-bodegacatceo-x-reddit-collectible-av"],
  "u/JoycevonD": ["joy-girls-club-x-reddit-collectible-avatars"],
}

SLUG_TO_TIERS = {
  "imagination-station-x-reddit-collectible-avatars": ["Big City Bear", "Cone Head", "Kid Rexie"],
  "the-butterfly-garden-x-reddit-collectible-avatars": ["Minted Monarch", "Butterfly of Diamonds", "Mutant Monarch"],
  "growl-gang-x-reddit-collectible-avatars": ["Bow Wow Bandits", "Speedy Demons", "Pounce Patrol"],
  "enlightenment-x-reddit-collectible-avatars": ["Raiza", "Etsuko", "Miran"],
  "drag-queens-of-big-gay-baby-x-reddit-collectible": ["April May", "Miss Ophelia Surprise", "Hydrogen Purroxide"],
  "creatures-of-the-nighties-x-reddit-collectible": ["Possum", "Dark Wolf", "Red Bat"],
  "joy-girls-club-x-reddit-collectible-avatars": ["Joy Kawaii Cowgirl", "Disco Queen Joy Girl", "Joy Kawaii Material Girl"],
  "avatar-rock-out-x-reddit-collectible-avatars": ["Les Rock", "Lara Lava", "Julia Jewels"],
  "protectors-of-the-forest-x-reddit-collectible-avat": ["Dragonfly", "Butterfly", "Birdie"],
  "bites-of-brazil-x-reddit-collectible-avatars": ["Sandro", "Flor", "Maria"],
  "cute-cool-and-creepy-x-reddit-collectible-avatars": ["Cat Fish", "Ancestral Tree", "Golden Hands"],
  "creatures-without-pants-x-reddit-collectible-avata": ["Avataur", "Medusatar", "Scalatar"],
  "lightspeed-lads-x-reddit-collectible-avatars": ["Bloopy McBloopface", "Dr. Morris Von Wrinklebrain", "Battery Bot"],
  "growl-gang-x-reddit-collectible-avatars": ["Bow Wow Bandits", "Speedy Demons", "Pounce Patrol"],
  "old-school-cool-x-reddit-collectible-avatars": ["Silver Age Comics", "Classic Animation", "Old-Timey Comedian"],
  "aylia-x-reddit-collectible-avatars": ["Maia", "Maru", "Bim"],
  "magic-of-the-woods-x-reddit-collectible-avatars": ["Bewitching Eyes", "So Much Truffle", "Flower Fairy"],
  "cute-snacks-x-reddit-collectible-avatars": ["Mouse au Chocolat", "Avo Cato", "Hot Dog"],
  "peculiar-gang-x-reddit-collectible-avatars": ["Redd Mummy", "Mr. GeeOd", "Cheeky Beak"],
  "gettin-groovy-x-reddit-collectible-avatars": ["Groovy", "Lava Lamp Avatar", "Euphoric Swirls"],
  "wearing-your-emotions-x-reddit-collectible-avatars": ["Mio Armor", "Mia Flames", "Diamond Diablo"],
  "i-quit-my-job-to-be-an-artist-x-reddit-collectibl": ["Frustrated", "Progress", "Confidence"],
  "baked-goods-evils-x-reddit-collectible-avatars": ["B•E•N•O•T•A•F•R•A•I•D", "Boroborygmius", "Sweet Providence"],
  "enlightenment-x-reddit-collectible-avatars": ["Raiza", "Etsuko", "Miran"],
  "doodle-collection-x-reddit-collectible-avatars": ["Knoo", "S'moore", "Stoo"],
  "foustlings-x-reddit-collectible-avatars": ["Classic Foustling", "Rainbow Foustling", "Fishy Foustling"],
  "the-senses-x-reddit-collectible-avatars": ["The Eyes", "The Mouths", "The Hands"],
  "the-minds-eyes-x-reddit-collectible-avatars": ["Good Morning Sunshine", "Mystic Fingers", "Vegan Brains"],
  "natsukashii-x-reddit-collectible-avatars": ["Yamata", "Kitsune", "Yami"],
  "5-boro-bodega-x-reddit-collectible-avatars": ["deadass from ny", "Pickle Guy", "Gummy"],
  "celestial-assembly-x-reddit-collectible-avatars": ["Series-137", "Dr. Nickelmittens", "The Assembler"],
  "spooky-season-tirli-x-reddit-collectible-avatars": ["Hellbent Over Pizza", "Death by Cuddling", "Snooze Paralysis"],
  "spooky-season-stuttervoid-x-reddit-collectible-ava": ["SONRISA", "Faceless", "Blood Orange"],
  "spooky-season-substantial-law-910-x-reddit-collect": ["Earthling", "Lunarian", "Mars"],
  "spooky-season-worsttwitchever-x-reddit-collectible": ["THE VISION", "THE MUTATION", "THE FAILED EXPERIMENT"],
  "spooky-season-rojom-x-reddit-collectible-avatars": ["The Sun", "The Moon", "Cosmic Abyss"],
  "spooky-season-poieeeyee-x-reddit-collectible-avata": ["Night Guard", "Hybrid 693", "Midas Touch"],
  "spooky-season-aliciafreemandesigns-x-reddit-collec": ["Batty for Halloween", "In-tree-guing", "Not so Fungi"],
  "spooky-season-genuineardvark-x-reddit-collectible": ["Eve, Cataclysm Engine [000]", "Sebastian, the Blood Moon", "Persephone, Aspect of Hades"],
  "spooky-season-earthtoplanet-x-reddit-collectible-a": ["ECLIPSE", "HELIX", "AWAKEN"],
  "spooky-season-oana193-x-reddit-collectible-avatars": ["Orpheus the Thirsty", "Naga the Basilisk", "Wildfire Demon"],
  "spooky-season-tfoust10-x-reddit-collectible-avatar": ["Illusionist Foustling", "Ghost Foustling", "Fake Foustling"],
  "spooky-season-conall-in-space-x-reddit-collectible": ["Unmentionable One", "Series-66", "The Imprisoned"],
  "spooky-season-avirenft-x-reddit-collectible-ava": ["Lil' Bummer", "Lil' Chaos", "Lil' Split"],
  "spooky-season-eando9745-x-reddit-collectible-avata": ["Music Man", "Skyborg", "Technical Difficulty"],
  "spooky-season-dubbl3bee-x-reddit-collectible-avata": ["Enya Enchantress", "Garth Guardian", "Floyd Flocculent"],
  "spooky-season-raunchyrancor-x-reddit-collectible-a": ["Creature of the Chill", "Under the Sea", "Ocean Explorer of Love"],
  "spooky-season-treasureofophiel-x-reddit-collectibl": ["Restriction of Dreams", "R•E•M•A•I•N•C•A•L•M", "Mister Charles’ Secret"],
  "spooky-season-puzzled-panther-x-reddit-collectible": ["Brundlecat", "The New Fur", "Milk O'blivion"],
  "spooky-season-thefattybagz-x-reddit-collectible-av": ["The Vessel", "The Vile One", "Mr. 2 Sweet"],
  "spooky-season-baldtuesdays-x-reddit-collectible": ["The Unidentified", "HandFull", "Skin and Bones"],
  "spooky-season-laura-dumitriu-x-reddit-collectible": ["The Robot", "The Devil", "SnakeEye"],
  "spooky-season-sys32template-x-reddit-collectible-a": ["Alt Account"],
  "spooky-season-bodegacatceo-x-reddit-collectible-av": ["GUARDIAN OF THE REALMS", "EYE OF THE BEHOLDER", "BINDED SOULS"],
  "spooky-season-tandizojere-x-reddit-collectible-ava": ["Tina", "The Knower", "My Rotten Soldier"],
  "spooky-season-canetoonist-x-reddit-collectible-ava": ["Cosplay", "Spooky Spaghetti", "Final Boss"],
  "spooky-season-fmarxy-x-reddit-collectible-avatars": ["Glowstickman", "Leave me alone big bro"],
  "spooky-season-hoppy-doodle-x-reddit-collectible-av": ["Ooni Roo", "Look Throo-1000", "Queen Tarantoola"],
}

AVATAR_TOKENIDS = {
  "Big City Bear": 1200,
  "Cone Head": 300,
  "Kid Rexie": 0,
  "Minted Monarch": 0,
  "Butterfly of Diamonds": 1500,
  "Mutant Monarch": 2400,
  "Bow Wow Bandits": 0,
  "Speedy Demons": 1500,
  "Pounce Patrol": 1840,
  "Raiza": 0,
  "Etsuko": 1500,
  "Miran": 1900,
  "April May": 0,
  "Miss Ophelia Surprise": 1500,
  "Hydrogen Purroxide": 2400,
  "Possum": 0,
  "Dark Wolf": 1500,
  "Red Bat": 1900,
  "Joy Kawaii Cowgirl": 0,
  "Disco Queen Joy Girl": 1500,
  "Joy Kawaii Material Girl": 1900,
  "Les Rock": 0,
  "Lara Lava": 1500,
  "Julia Jewels": 2400,
  "Dragonfly": 0,
  "Butterfly": 1500,
  "Birdie": 2400,
  "Sandro": 1200,
  "Flor": 0,
  "Maria": 900,
  "Cat Fish": 0,
  "Ancestral Tree": 750,
  "Golden Hands": 1250,
  "Avataur": 0,
  "Medusatar": 1500,
  "Scalatar": 2400,
  "Bloopy McBloopface": 600,
  "Dr. Morris Von Wrinklebrain": 200,
  "Battery Bot": 0,
  "Silver Age Comics": 0,
  "Classic Animation": 1500,
  "Old-Timey Comedian": 2400,
  "Maia": 0,
  "Maru": 1500,
  "Bim": 1840,
  "Bewitching Eyes": 600,
  "So Much Truffle": 200,
  "Flower Fairy": 0,
  "Mouse au Chocolat": 1200,
  "Avo Cato": 0,
  "Hot Dog": 900,
  "Redd Mummy": 0,
  "Mr. GeeOd": 1500,
  "Cheeky Beak": 1900,
  "Groovy": 0,
  "Lava Lamp Avatar": 1500,
  "Euphoric Swirls": 2300,
  "Mio Armor": 0,
  "Mia Flames": 1500,
  "Diamond Diablo": 2250,
  "Frustrated": 0,
  "Progress": 1500,
  "Confidence": 2400,
  "B•E•N•O•T•A•F•R•A•I•D": 0,
  "Boroborygmius": 1165,
  "Sweet Providence": 1993,
  "Knoo": 0,
  "S'moore": 1500,
  "Stoo": 2400,
  "Classic Foustling": 0,
  "Rainbow Foustling": 1500,
  "Fishy Foustling": 2400,
  "The Eyes": 600,
  "The Mouths": 200,
  "The Hands": 0,
  "Good Morning Sunshine": 0,
  "Mystic Fingers": 1500,
  "Vegan Brains": 2400,
  "Yamata": 0,
  "Kitsune": 1500,
  "Yami": 1900,
  "deadass from ny": 0,
  "Pickle Guy": 1500,
  "Gummy": 2400,
  "Series-137": 0,
  "Dr. Nickelmittens": 1500,
  "The Assembler": 2333,
  "Hellbent Over Pizza": 1050,
  "Death by Cuddling": 0,
  "Snooze Paralysis": 700,
  "SONRISA": 0,
  "Faceless": 1300,
  "Blood Orange": 1100,
  "Earthling": 533,
  "Lunarian": 0,
  "Mars": 322,
  "THE VISION": 0,
  "THE MUTATION": 1100,
  "THE FAILED EXPERIMENT": 1866,
  "The Sun": 0,
  "The Moon": 1100,
  "Cosmic Abyss": 1900,
  "Night Guard": 0,
  "Hybrid 693": 1100,
  "Midas Touch": 1893,
  "Batty for Halloween": 0,
  "In-tree-guing": 1900,
  "Not so Fungi": 1100,
  "Eve, Cataclysm Engine [000]": 0,
  "Sebastian, the Blood Moon": 1100,
  "Persephone, Aspect of Hades": 1866,
  "ECLIPSE": 0,
  "HELIX": 1100,
  "AWAKEN": 1500,
  "Orpheus the Thirsty": 0,
  "Naga the Basilisk": 1100,
  "Wildfire Demon": 1400,
  "Illusionist Foustling": 0,
  "Ghost Foustling": 1399,
  "Fake Foustling": 1100,
  "Unmentionable One": 0,
  "Series-66": 1100,
  "The Imprisoned": 1550,
  "Lil' Bummer": 0,
  "Lil' Chaos": 1099,
  "Lil' Split": 1532,
  "Music Man": 0,
  "Skyborg": 1100,
  "Technical Difficulty": 1450,
  "Enya Enchantress": 0,
  "Garth Guardian": 1100,
  "Floyd Flocculent": 1533,
  "Creature of the Chill": 650,
  "Under the Sea": 0,
  "Ocean Explorer of Love": 400,
  "Restriction of Dreams": 0,
  "R•E•M•A•I•N•C•A•L•M": 450,
  "Mister Charles’ Secret": 1327,
  "Brundlecat": 500,
  "The New Fur": 250,
  "Milk O'blivion": 0,
  "The Vessel": 0,
  "The Vile One": 1300,
  "Mr. 2 Sweet": 1100,
  "The Unidentified": 650,
  "HandFull": 250,
  "Skin and Bones": 0,
  "The Robot": 0,
  "The Devil": 1100,
  "SnakeEye": 1600,
  "Alt Account": 0,
  "EYE OF THE BEHOLDER": 450,
  "GUARDIAN OF THE REALMS": 1250,
  "BINDED SOULS": 0,
  "Tina": 0,
  "The Knower": 1100,
  "My Rotten Soldier": 1800,
  "Cosplay": 0,
  "Spooky Spaghetti": 1100,
  "Final Boss": 1865,
  "Glowstickman": 600,
  "Leave me alone big bro": 0,
  "Ooni Roo": 0,
  "Look Throo-1000": 1100,
  "Queen Tarantoola": 1850,
}

SLUG_TO_BUCKETS = {}
for slug in SLUG_TO_TIERS:
    tokenids = [(tier, AVATAR_TOKENIDS[tier]) for tier in SLUG_TO_TIERS[slug]]
    SLUG_TO_BUCKETS[slug] = sorted(tokenids, key=lambda x: x[1])
